# databases:
#   - name: kst-db-prod
#     databaseName: kst_db
#     user: kst_admin
#     plan: free

services:
  # 1. Backend API
  - type: web
    name: kst-backend
    runtime: image
    image:
      url: andremugabo/kst-backend:latest
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      # Neon.tech Connection String
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_hJdj0ZKqgR5v@ep-fragrant-firefly-ahhqfjb9-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3005
      - key: UPLOAD_MODE
        value: cloud
      - key: CLOUD_NAME
        value: your_cloud_name
      - key: API_KEY
        value: your_api_key
      - key: API_SECRET
        value: your_api_secret

  # 2. Public Frontend
  - type: web
    name: kst-frontend-public
    runtime: image
    image:
      url: andremugabo/kst-frontend:latest
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://kst-backend.onrender.com/api

  # 3. Admin Portal
  - type: web
    name: kst-admin-portal
    runtime: image
    image:
      url: andremugabo/kst-admin:latest
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://kst-backend.onrender.com/api
