# databases:
#   - name: kst-db-prod
#     databaseName: kst_db
#     user: kst_admin
#     plan: free

services:
  # 1. Backend API
  - type: web
    name: kst-backend
    runtime: image
    image:
      url: andremugabo/kst-backend:prod
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      # Neon.tech Connection String
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_hJdj0ZKqgR5v@ep-fragrant-firefly-ahhqfjb9-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: BACKEND_URL
        value: https://kst-backend.onrender.com
      # Cloudinary - persistent image storage
      - key: UPLOAD_MODE
        value: cloud
      - key: CLOUD_NAME
        value: dteiwjwwn
      - key: API_KEY
        value: "766782647789835"
      - key: API_SECRET
        value: rRcKsOwU7yvrzf91EMCpelESzmQ

  # 2. Public Frontend
  - type: web
    name: kst-frontend
    runtime: image
    image:
      url: andremugabo/kst-frontend:prod
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://kst-backend.onrender.com/api
      - key: VITE_UPLOAD_URL
        value: https://kst-backend.onrender.com

  # 3. Admin Portal
  - type: web
    name: kst-admin
    runtime: image
    image:
      url: andremugabo/kst-admin:prod
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://kst-backend.onrender.com/api
      - key: VITE_UPLOAD_URL
        value: https://kst-backend.onrender.com
